# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.IntegerField(default=1)),
                ('minimal_precision', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dotplot',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_plot.Sequence'),
        ),
    ]
