# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_plot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotplot',
            name='sequence',
        ),
        migrations.AddField(
            model_name='dotplot',
            name='first_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotplot',
            name='second_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotplot',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
